.AE:
- r: mena
- DUBAI
.AL:
- r: cee
- TIRANA
.AN:
- r: cala
- WILLEMSTAD
.AR:
- r: cala
- BUENOS AIRES!
- CAPITAL FEDERAL
- DEL VISO
- MUNRO
- SAN SALVADOR
.AT:
- r: weur
- DONAU
- LINZ
- VIENNA!
- WIEN
.AU:
- r: apac
- ADELAIDE
- BELCONNEN
- BRISBANE
- CANBERRA
- CHATSWOOD
- CLOISTERS SQ
- MACQUARIE PARK
- MELBOURNE!
- MILTON
- MULGRAVE
- NORTH RYDE
- PERTH
- RICHMOND
- ST LEONARDS
- SYDNEY
.AZ:
- r: weur
- BAKU
.BA:
- r: cee
- MOSTAR!
.BB:
- r: cala
- ST MICHAEL
.BD:
- r: apac
- DHAKA
- GOPALGONJ
.BE:
- r: weur
- LIEGE
- ANTWERPEN
- BRUSSELS
- BRUXELLE
- GENT
- MECHELEN
- ZAVENTEM
.BG:
- r: weur
- SOFIA!
.BH:
- r: mena
- MANAMA
- SALMANYA!
.BM:
- r: cala
- HAMILTON
.BO:
- r: cala
- LA PAZ
.BR:
- r: cala
- BRASILIA
- RIO DE JANEIRO
- SAO PAULO!
.BS:
- r: cala
- FREEPORT
- NASSAU
.BW:
- r: weur
- GABORONE
.BY:
- r: cee
- BELGRADE
- MINSK!
.BZ:
- r: cala
- BELIZE
- JANEIRO
.CA:
- r: can
.CH:
- r: weur
- AARAU
- BASEL
- BERN
- BIEL
- BINZ
- CHAMBSY
- CHESEAUX
- GENEVA
- LAUSANNE
- LIESTAL
- PRATTELN
- ZUERICH!
- ZURICH
.CL:
- r: cala
- SANTIAGO
- VALDIVIA
.CN:
- r: apac
- SHENZHEN
- BEIJING!
- CHENGDU
- FUZHOU
- GUANGZHOU
- HANGZHOU
- HUNAN
- NANJING
- PUTIAN CITY
- SHANGHAI
- SHENZHEN
- SUZHOU CITY
- TANGGU
- XIAMEN CITY
- YUEXIUNAN
- ZHEJIANG
.CO:
- r: cala
- BOGOTA!
- MEDELLIN
- PEREIRA
.CR:
- r: cala
- OESTE!
- SAN JOSE
- SAN PEDRO
.CS:
- r: weur
- BEOGRAD
.CU:
- r: cala
- HABANA
.CY:
- r: weur
- NICOSIA!
.CZ:
- r: cee
- OLOMOUC
- PRAGUE
- PRAHA
.DE:
- r: weur
- BAD HOMBURG
- AACHEN
- BERLIN
- BIELEFELD
- BONN!
- DARMSTADT
- DORTMUND
- DRESDEN
- DUESSELDORF
- ERFURT
- ESCHBORN
- ESSEN
- FRANKFURT
- FRIEDRICHSHAFEN
- HAMBURG
- HAMM
- HAUSHAM
- HEIDELBERG
- HERFORD
- HUERTH
- KARLSRUHE
- KASSEL
- KEMPTEN
- KOELN
- KONSTANZ
- LEIPZIG
- MUENCHEN
- MUNCHEN
- MUNICH
- NORDERSTEDT
- NUERNBERG
- OERING
- PADERBORN
- ROTH
- SAARBRUECKEN
- STUTTGART
- SULZBACH
- WALLDORF
.DK:
- r: weur
- ALBERTSLUND
- BALLERUP
- COPENHAGEN!
- FARSTA-STOCKHOLM
- GLOSTRUP
- KOEBENHAVN
- KOLDING
- LYNGBY
- TRANBJERG
- VIBY
.DO:
- r: cala
- SANTO DOMINGO
.EC:
- r: cala
- GUAYAQUIL
- QUITO!
.EE:
- r: weur
- TALLINN
.EG:
- r: mena
- CAIRO
.ES:
- r: weur
- BARCELONA
- DERIO
- GALICIA
- MADRID!
- OVIEDO ASTURIAS
- VALENCIA
- VIGO
- ZAMUDIO
.UG:
- r: afr
- KAMPALA
.FI:
- r: weur
- ELISA
- ESPOO
- HELSINKI!
- SONERA
.FR:
- r: weur
- BOULOGNE BILLANCOURT
- CESSON-SEVIGNE
- CHAMPS SUR MARNE
- COLOMBELLES
- COURTABOEUF
- ECHIROLLES
- EVRY
- ISSY LES MOULINEAUX
- LE PLESSIS ROBINSON
- LILLE
- MARCOUSSIS
- MEUDON-LA-FORET
- NEUILLY
- NICE
- PARIS!
- SURESNES
- TOULOUSE
- VELIZY
.GB:
- r: weur
- ATTLEBOROUGH
- BARNWOOD
- BATH
- BIRMINGHAM
- BOURNEMOUTH
- BRADFORD
- BRIGHTON
- BRISTOL
- DOUGLAS
- DURHAM
- EDINBURGH
- EWLOE
- EXETER
- GLASGOW
- GOSPORT
- GUILDFORD
- HATFIELD
- HAVANT
- HOLYWELL
- HOOK
- IRLAM
- LEEDS
- LONDON!
- MAIDENHEAD
- MANCHESTER
- MILTON KEYNES
- NEWBURY
- OXFORD
- READING
- ROCHDALE
- SHEFFIELD
- SLOUGH
- ST HELIER
- SWINDON
- TELFORD
- WARRINGTON
- WATERLOO
- WINCHESTER
- WOKING
.GD:
- r: cala
- GEORGE'S
.GE:
- r: cee
- TBILISI
.GR:
- r: weur
- ATHENS!
- PEANIA ATTIKA
.GT:
- r: cala
- GUATEMALA
.GU:
- r: cala
- DEDEDO
.HK:
- r: apac
- HONG KONG!
- KOWLOON
.HN:
- r: cala
- LA CEIBA
- SAN PEDRO SULA
- SULA
- TEGUCIGALPA
.HR:
- r: cee
- ZAGREB
.HU:
- r: cee
- TOROKBALINT
- BUDAORS
- BUDAPEST
- KECSKEMET
- SZEGED
- TOROKBALINT
.ID:
- r: apac
- BANDUNG
- JAKARTA
.IE:
- r: weur
- DUBLIN!
- DUNDALK
- GALWAY
- VIENNA
.IL:
- r: mena
- HAIFA!
- HERZILIA PITUACH
- JERUSALEM
- PETACH TIKVA
- PETACH-TIKVA
- RAMAT GAN
- ROSH HA'AYIN
- TEL AVIV
- YAKUM
.IN:
- r: apac
- HYDERABAD
- AHMEDABAD
- BANGALORE
- BHOPAL
- BOMBAY
- CHENNAI
- GHANSOLI
- GURGAON
- HYDERABAD
- JAIPUR
- KANPUR
- MUMBAI
- NEW DELHI!
- DELHI
- NOIDA
- ORISSA
- PUNE
- PUNJAB
- SIRUSERI
- SURAT
- THIRU
- TURBHE
.IR:
- r: mena
- KERMANSHAH
- TEHRAN!
- YAZD
.IS:
- r: weur
- REYKJAVIK!
.IT:
- r: weur
- CAGLIARI
- GENOVA
- IVREA
- MILAN
- NAPOLI
- PADOVA
- PESCARA
- PISA
- ROMA
- ROME!
- SEGRATE
- TORINO
- TRENTO
- UDINE
.JM:
- r: cala
- KINGSTON
.JO:
- r: mena
- AMMAN!
.JP:
- r: apac
- AHARA-KU
- CHIYODA
- MINATO-KU
- TOKYO!
.KN:
- r: cala
- BASSETERRE
.KR:
- r: apac
- KANGNAM-KU
- SEOUL!
.KW:
- r: mena
- DASMAN
- KUWAIT
- SAFAT
.KY:
- r: cala
- TOWN
.KZ:
- r: cee
- ALMATY
.LB:
- r: mena
- BEIRUT!
.LC:
- r: cala
- CASTRIES
.LK:
- r: apac
- COLOMBO!
.LT:
- r: weur
- KAUNAS
- VILNIUS
.LU:
- r: weur
- BETZDORF
- STEINSEL
.LV:
- r: weur
- CESIS
- LIVANI
- RIGA
.MD:
- r: cee
- CHISINAU
.MK:
- r: cee
- SKOPJE!
.MM:
- r: apac
- YANGON
.MO:
- r: apac
- MACAU
.MT:
- r: weur
- MARSA
.MU:
- r: afr
- EBENE
.MV:
- r: apac
- MALDIVES
.MX:
- r: cala
- ACAPULCO
- CANCUN
- CUERNAVACA
- GARZA GARCIA
- GUADALAJARA
- JUREZ
- MEXICO CITY
- MEXICO DF!
- MONTERREY
- TIJUANA
.MY:
- r: apac
- KUALA LUMPUR
.NG:
- r: emea
- LAGOS!
.NI:
- r: cala
- MANAGUA
.NL:
- r: weur
- AALSMEER
- ALMERE
- AMERSFOORT
- AMSTELVEEN
- AMSTERDAM!
- BREDA
- DEN HAAG
- DIEMEN
- DRONTEN
- EDE
- EINDHOVEN
- GRONINGEN
- HILVERSUM
- HOOFDDORP
- KAMPERLAND
- LEEUWARDEN
- LINCOLN
- MAASTRICHT
- NAALDWIJK
- NIJMEGEN
- ROTTERDAM
- SCHIPHOL RIJK
- THE HAGUE
- TOROLA
- UTRECHT
.NO:
- r: weur
- BERGEN
- FORNEBU
- LYSAKER
- OSLO
- STAVANGER
.NP:
- r: apac
- KATHMANDU
- LALITPUR
.NZ:
- r: apac
- AUCKLAND!
.OM:
- r: mena
- MUSCAT
.PA:
- r: cala
- PANAMA
.PE:
- r: cala
- LIMA
.PH:
- r: apac
- MAKATI CITY!
- MANDALUYONG CITY
- MANILA
- QUEZON CITY
.PK:
- r: apac
- ISLAMABAD!
- KARACHI
- LAHORE
.PL:
- r: cee
- GDANSK
- GDYNIA
- KATOWICE
- KRAKOW
- LODZ
- MIELEC
- OSLO
- POZNAN
- RADZIONKOW
- TARNOW
- TYCHY
- WARSAW
- WARSZAWA!
- WROCLAW
.PR:
- r: cala
- LUQUILLO
- MERCEDITA
- SAN JUAN
- VEGA BAJA
.PS:
- r: mena
- NABLUS!
.PT:
- r: weur
- AMADORA
- CARNAXIDE
- LISBOA!
- LISBON
- PALMELA
- PORTO
.PY:
- r: cala
- ASUNCION
- FERNANDO DE LA MORA
.QA:
- r: mena
- DOHA
.RO:
- r: cee
- ALBA IULIA
- BUCHAREST
- BUCURESTI
- JUD ALBA
.RS:
- r: cee
- BELGRADE
- BEOGRAD
- PRISHTINA
.RU:
- r: cee
- IRKUTSK
- KAZAN
- MOSCOW!
- MOSKOW
- NIZHNIY NOVGOROD
- NIZHNY NOVGOROD
- NOVOCHERKASSK
- NOVOSIBIRSK
- PENZA
- ROSTOV-ON-DON
- ROSTOV ON DON
- ROSTOV
- SAINT PETERSBURG
- SAINT-PETERSBURG
- SAMARA
- ST PETERSBURG
- ST-PETERSBURG
- TAMBOV
- TOGLIATTI
- TOMSK
- TOROLA
- VOLGOGRAD
- YEKATERINBURG
.SA:
- r: mena
- DHAHRAN
- RIYADH!
.SC:
- r: mena
- VICTORIA!
.SE:
- r: weur
- FARSTA
- GOTEBORG
- HANINGE
- KARLSKRONA
- KISTA
- LINKOPING
- LINK*PING
- MALMO
- MALMOE
- NACKA
- OREBRO
- SOLLENTUNA
- SOLNA
- STOCKHOLM!
- SUNDBYBERG
- UMEA
.SG:
- r: apac
- SINGAPORE!
.SI:
- r: cee
- KRANJ
- LJUBLJANA!
- MARIBOR
.SK:
- r: cee
- BRATISLAVA
.SV:
- r: cala
- SAN SALVADOR
.SY:
- r: mena
- DAMASCUS!
.TC:
- r: cala
- HILLS
.TH:
- r: apac
- BANGKOK!
- NONTHABURI
.TR:
- r: weur
- ANKARA!
- ISTANBUL
.TT:
- r: cala
- PORT OF SPAIN
- ST JAMES
.TW:
- r: apac
- TAICHUNG
- TAIPEI
.UA:
- r: cee
- BOYARKA
- CHERKASSY
- DNEPROPETROVSK
- DONETSK
- KHARKIV
- KHARKOV
- KHERSON
- KIEV!
- KRIVOY ROG
- KYIV
- NIKOPOL
- ODESSA
- RIVNE
- VINNITSA
.US:
- r: usa
- WASHINGTON!
.UY:
- r: cala
- MONTEVIDEO
.VE:
- r: cala
- CARACAS
.VG:
- r: cala
- TOWN
.VI:
- r: cala
- THOMAS
.VN:
- r: apac
- HA NOI
- HANOI
- HCMC
.YE:
- r: mena
- SANAA!
.ZA:
- r: afr
- JOHANNESBURG!
- WESTERN CAPE
.ZW:
- r: afr
- HARARE
